### ISSUE TITLE
Comments on 19Apr draft

### ISSUE THREAD

**Issue by erex** [maiers94/rpatrec#2]
Stephan

A quick scan didn't flag up any new issues for me; I don't feel the necessity of another meeting.  Have a look at my comments and see if you feel there is a need to meet.

[report-corrections3-ER.docx](https://github.com/maiers94/rpatrec/files/942012/report-corrections3-ER.docx)

**Comment by maiers94** [comment]
Dear Dr Rexstad, 
Thanks a lot for your comments! I will incorporate those, they all make perfect sense to me, I do not think we need to meet again before the deadline.

Do you think there is anything missing in the report or do you think it is complete and ready for submission with the final changes added to it? 

I am currently working on the documentation and am expanding it significantly. I also managed to get the package uploaded onto CRAN - the final fully documented version will be the first update to the CRAN version (currently on 0.9.1). [CRAN will however still take their time until they make the windows binaries available - it already works on Linux!]. I will let you know when I am ready working on the documentation, so that we can test the OneDrive hand-in procedure for the final binary package.

thanks again,

Stephan

**Comment by erex** [comment]
I think the dissertation is sufficiently thorough.  Have another read-through yourself and make your decision.

I'm impressed that you have uploaded the package to CRAN; recognise that is not a requirement of the project.

I await your signal for testing the OneDrive upload.

**Comment by maiers94** [comment]
https://1drv.ms/u/s!AuUKxnS7JRhPbX3nSkthxSTzZv0

Here is the link for the binary build, I also emailed you this.

**Comment by erex** [comment]
Just installed from OneDrive.  seems to be OK.  
* You can alter the DESCRIPTION file to give it a version number that makes more sense.
* both vignettes are visible (as html/rmd/R code).  Would be nice if they had more interesting names
    * Recognising patterns - simulated data
    * Recognising patterns - stock market data
* didn't look closely at documentation previously, looks ~adequate now, can always more
